graph_dataset:
    ERmodel: True
    p1ER: 0.3
    p2ER: 0.08
    Num_nodes: 100
    Num_grafi_per_tipo: 100
    
training:
    learning_rate: 0.005
    epochs: 1500
    batch_size: 150
    percentage_train: 0.7
    criterion: 'MSELoss'  # 'CrossEntropy'
    
model:
    layers: 3
    num_neurons: 64
    num_last_neurons: 1
    
device: 'gpu'