graph_dataset:
    ERmodel: True
    regular: False
    confmodel: False
    continuous_p: False
    random_node_feat: False
    list_p: [0.05, 0.2] #, 0.3, 0.4, 0.5, 0.6]
    range_p: [0.05, 0.6]
    Num_nodes: 300
    Num_grafi_per_tipo: 200
    Num_grafi_totali: 1000
    list_degree: [10, 20, 30]
    
    
training:
    #mode1 = 'classification', CrossEntropyLoss, '1-hot', 'n_class'
    #mode2 = 'classification', BCELoss, '{0,1}', 1
    #mode3 = 'regression', MSELoss, 'p', 1}
    mode: 'mode2'
    learning_rate: 0.01
    epochs: 2000
    batch_size: 700
    percentage_train: 0.7
    earlystop_patience: 250
    epochs_model_checkpoint: [-1]
    save_best_model: True
    every_epoch_embedding: False
    shuffle_dataset: True
    
model:
    last_layer_dense: True
    GCNneurons_per_layer: [1, 16, 16, 1]
    neurons_last_linear: [8, 8, 1]  # 1 nodo finale
    freezeGCNlayers: True
    autoencoder: False
    put_batchnorm: False
    final_pool_aggregator: True
    put_dropout: False
    node_features_dim: 1
    init_weights: 'xavier_normal'
    
logging:
    train_step_print: 100
    
device: 'gpu'