graph_dataset:
    ERmodel: False
    regular: False
    confmodel: True
    continuous_p: True
    list_p: [0.05, 0.3] #, 0.3, 0.4, 0.5, 0.6]
    range_p: [0.05, 0.6]
    Num_nodes: [350, 350, 350] #, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500]
    Num_grafi_per_tipo: 100
    Num_grafi_totali: 400
    list_degree: [4, 50]
    random_node_feat: False
    list_exponents: [5.5, 6.0, 6.5] #, -1.5, -1.9, -2.0, -2.2, -2.5, -2.7, -2.9, -3.1, -3.3, -3.5, -3.7, -3.9, -4.1, -4.3, -4.5, -1.2]
    
training:
    #mode1 = 'classification', CrossEntropyLoss, '1-hot', 'n_class'
    #mode2 = 'classification', BCEWithLogitsLoss, '{0,1}', 1
    #mode3 = 'regression', MSELoss, 'p', 1}
    mode: 'mode1'
    learning_rate: 0.01
    epochs: 0
    batch_size: 400
    percentage_train: 0.7
    earlystop_patience: 30
    epochs_model_checkpoint: [-1]
    save_best_model: False
    every_epoch_embedding: True
    shuffle_dataset: True
    
model:
    last_layer_dense: True
    GCNneurons_per_layer: [1, 32, 16, 1]  
    neurons_last_linear: [10, 10, 3]
    freezeGCNlayers: True
    autoencoder: False
    put_batchnorm: False
    put_dropout: False
    final_pool_aggregator: True
    node_features_dim: 1
    init_weights: 'eye'
    
logging:
    train_step_print: 100
    
device: 'gpu'