graph_dataset:
    ERmodel: True
    regular: False
    confmodel: False
    sbm: False
    real_dataset: False
    real_data_name:  'BACI'  #'REDDIT-BINARY'   #
    continuous_p: False
    random_node_feat: False
    list_p: [0.3, 0.2, 0.15, 0.1] #, 0.01]
    range_p: [0.01, 0.5]
    community_probs: [[[0.25, 0.01], [0.01, 0.1]], [[0.4, 0.01], [0.01, 0.3]], [[0.4, 0.01], [0.01, 0.1]]]  # num nodi * num classi * num comunità
    Num_nodes: [200, 200, 200, 200] # , 200]
    Num_grafi_per_tipo: 3
    Num_grafi_totali: 1000
    list_degree: [4, 50]
    list_exponents: [-2.2, -2.5, -2.8, -3.0, -3.2, -3.5, -3.7]
    
    
    
training:
    #mode1 = 'classification', CrossEntropyLoss, '1-hot', 'n_class'
    #mode2 = 'classification', BCELoss, '{0,1}', 1
    #mode3 = 'regression', MSELoss, 'p', 1}
    mode: 'mode1'
    learning_rate: 0.001
    epochs: 2000000
    epochs_list_points: 50
    batch_size: 200
    percentage_train: 0.7
    earlystop_patience: 500
    epochs_model_checkpoint: [-1]
    save_best_model: False
    every_epoch_embedding: True
    shuffle_dataset: False
    calculate_metrics: True
    optimizer: SGD
    
model:
    last_layer_dense: False
    GCNneurons_per_layer: [1, 32, 32, 32]
    neurons_last_linear: [16, 16, 2]
    freezeGCNlayers: False
    autoencoder: True
    autoencoder_confmodel: False
    autoencoder_graph_ae: False
    put_batchnorm: True
    final_pool_aggregator: True
    put_dropout: False
    node_features_dim: 1
    init_weights:  'xavier_normal' #  'kaiming_uniform'  'normal'
    activation: 'ELU'   # LeakyRELU , Hardtanh, 'RELU' Tanh'
    last_layer_activation: 'RELU'
    
graph_ae_model:
    num_kernels: 2
    depth: 3
    comp_rate: 0.8
    GCNneurons_per_layer: [1,32,32,32]   
    
logging:
    train_step_print: 1000
    
device: 'gpu'