graph_dataset:
    ERmodel: True
    regular: False
    confmodel: False
    continuous_p: False
    random_node_feat: False
    list_p: [0.05, 0.3] #, 0.3, 0.4, 0.5, 0.6]
    range_p: [0.05, 0.6]
    Num_nodes: 300
    Num_grafi_per_tipo: 300
    Num_grafi_totali: 1000
    list_degree: [10, 20, 30]
    
training:
    #mode1 = 'classification', CrossEntropyLoss, '1-hot', 'n_class'
    #mode2 = 'classification', BCELoss, '{0,1}', 1
    #mode3 = 'regression', MSELoss, 'p', 1}
    mode: 'mode3'
    learning_rate: 0.01
    epochs: 8000
    batch_size: 150
    percentage_train: 0.7
    earlystop_patience: 10000
    
model:
    last_layer_dense: True
    neurons_per_layer: [1, 16, 8, 1]  # il primo elemento deve essere uguale alla dimensione delle feature del nodo
    autoencoder: False
    put_batchnorm: False
    final_pool_aggregator: True
    node_features_dim: 1
    
logging:
    train_step_print: 100
    
device: 'gpu'